### ISSUE TITLE
Stark fails to open

### ISSUE THREAD

**Issue by tdzl** [stark-contrast/stark-sketch-plugin#19]
Frequently having an issue where Stark fails to open – typically after I've used it once. Steps to reproduce:

1. Open Sketch and begin working
2. Open Stark (either via Runner or through the menu option)
3. Stark works successfully
4. Close Stark
5. Open Stark again to check another element
6. Nothing happens

Using:
Sketch 49.2
MacOs: High Sierra
Stark: 1.6

**Comment by creativename** [comment]
Same Issue, same specs. Anytime I close the plugin window, say to start using the contrast checker, Stark won't open again until I quit and reopen sketch.

**Comment by danilucaci** [comment]
Same here, it only works again if I open it from the sketch menu manually or if I open again sketch.

**Comment by imcatnoone** [comment]
Hey @danilucaci @creativename @tdzl sorry for the delay in response here. We've been heads down working on a fix for this as a team and alongside the Sketch team. Turns out, they broke the plugins when they were building Sketch 49. And odds are they're not pushing a fix for it given how close they are to a new release. However, we're happy to report there is a fix for this in Sketch 50.

I imagine there's a fix coming in the next couple of weeks. Seriously apologize for this hiccup and any inconvenience it has caused. We're right in the same boat with you given we use Stark too 😩

**Sidenote:** We're personally working on something to ensure issues with individual software programs never impact your ability to design properly for everyone.

**Comment by tdzl** [comment]
@imcatnoone thank you for the update! Looking forward to Sketch 50, and the fix for Stark.

**Comment by mfouquet** [comment]
Closing this out since it looks like Sketch 50 did the trick. Thanks everyone for providing the details to help track this down.
